name: Build & Deploy

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
          
      - name: Serverless Stack (SST) deploy
        uses: quenginedev/sst-deploy@v.1.3
        with:
          # AWS access key id
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # AWS secret access key
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # AWS region
          region: eu-west-1
          # The stage name (default is production)
          stage: prod
          
